SO/SolucionTecmein/TecmeinAplicacionWeb/Utilidades/ViewComponents/MenuUsuarioViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace TecmeinWebApp.Utilidades.ViewComponents
{
    public class MenuUsuarioViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            ClaimsPrincipal claimUser = HttpContext.User;
            string nombreUsuario = string.Empty;
            string urlFotoUsuario = string.Empty;

            if (claimUser != null && 
                claimUser.Identity.IsAuthenticated)
            {
                nombreUsuario =
                    claimUser
                    .Claims
                    .Where(c => c.Type == ClaimTypes.Name)
                    .Select(c => c.Value).SingleOrDefault();

                urlFotoUsuario = ((ClaimsIdentity)claimUser.Identity).FindFirst("UrlFoto").Value;
            }
            ViewData["nombreUsuario"] = nombreUsuario;
            ViewData["UrlFotoUsuario"] = urlFotoUsuario;

            return View();
        }
    } 
    
}

SO/SolucionTecmein/TecmeinAplicacionWeb/Utilidades/ViewComponents/MenuViewComponent.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TecmeinWebApp.Models.ViewModel;

using BLL.Interfaces;



namespace TecmeinWebApp.Utilidades.ViewComponents
{


    public class MenuViewComponent : ViewComponent
    {

        private readonly IMenuServices _menuServicio;
        private readonly IMapper _mapper;

        public MenuViewComponent(IMenuServices menuServices, IMapper mapper)
        {
            _mapper = mapper;
            _menuServicio = menuServices;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {

            ClaimsPrincipal claimsUser = HttpContext.User;
            List<MenuVM> listaMenu;

            if (claimsUser.Identity.IsAuthenticated)
            {
                string idUsuario =
                   claimsUser
                   .Claims
                   .Where(x => x.Type == ClaimTypes.NameIdentifier)
                   .Select(x => x.Value).SingleOrDefault();

                listaMenu =
                    _mapper
                        .Map<List<MenuVM>>(await _menuServicio
                                                 .ObtieneMenu(int.Parse(idUsuario)));
            }
            else
                listaMenu = new List<MenuVM>();


            return View(listaMenu);

        }


    }
}

SO/SolucionTecmein/TecmeinAplicacionWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TSI- @ViewData["Title"]</title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.css" rel="stylesheet">
    <link href="~/vendor/toastr/toastr.min.css" rel="stylesheet">
    <link href="~/vendor/sweetalert/sweetalert.css" rel="stylesheet">
    @await RenderSectionAsync("Estilos", required: false)
</head>


<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index","Home")">
                <div class="sidebar-brand-icon">
                    <i class="fas fa-desktop"></i>
                </div>
                <div class="sidebar-brand-text mx-3" href="#" >Tecmein </div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">
            @await Component.InvokeAsync("Menu")


            <!-- Divider --> 
            <hr class="sidebar-divider">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>
                        @await Component.InvokeAsync("MenuUsuario")
                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright Tecmein 2024</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>~/

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.js"></script>
    <script src="~/vendor/toastr/toastr.min.js"></script>
    <script src="~/vendor/sweetalert/sweetalert.js"></script>
    <script src="~/vendor/loadingoverlay/loadingoverlay.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>


</html>